/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1AcaRaInterface"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1AcaRaInterface.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "RaAcaCertRequest.h"
#include "AcaRaCertResponse.h"
#include <constr_CHOICE.h>
#ifndef	_AcaRaInterfacePdu_H_
#define	_AcaRaInterfacePdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AcaRaInterfacePdu_PR {
	AcaRaInterfacePdu_PR_NOTHING,	/* No components present */
	AcaRaInterfacePdu_PR_raAcaCertRequest,
	AcaRaInterfacePdu_PR_acaRaCertResponse
	/* Extensions may appear below */
	
} AcaRaInterfacePdu_PR;

/* AcaRaInterfacePdu */
typedef struct AcaRaInterfacePdu {
	AcaRaInterfacePdu_PR present;
	union AcaRaInterfacePdu_u {
		RaAcaCertRequest_t	 raAcaCertRequest;
		AcaRaCertResponse_t	 acaRaCertResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcaRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaRaInterfacePdu;
extern asn_CHOICE_specifics_t asn_SPC_AcaRaInterfacePdu_specs_1;
extern asn_TYPE_member_t asn_MBR_AcaRaInterfacePdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AcaRaInterfacePdu_H_ */
#include <asn_internal.h>
