/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "AprvBinaryTree.h"
#include "IndividualAprv.h"
#include <constr_CHOICE.h>
#ifndef	_AcpcPdu_H_
#define	_AcpcPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AcpcPdu_PR {
	AcpcPdu_PR_NOTHING,	/* No components present */
	AcpcPdu_PR_tree,
	AcpcPdu_PR_aprv
	/* Extensions may appear below */
	
} AcpcPdu_PR;

/* AcpcPdu */
typedef struct AcpcPdu {
	AcpcPdu_PR present;
	union AcpcPdu_u {
		AprvBinaryTree_t	 tree;
		IndividualAprv_t	 aprv;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcpcPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcpcPdu;

#ifdef __cplusplus
}
#endif

#endif	/* _AcpcPdu_H_ */
#include <asn_internal.h>
