/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Uint8.h"
#include "AcpcTreeId.h"
#include "IValue.h"
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#ifndef	_AprvHashCalculationInput_H_
#define	_AprvHashCalculationInput_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AprvHashCalculationInput */
typedef struct AprvHashCalculationInput {
	Uint8_t	 version;
	AcpcTreeId_t	 acpcTreeId;
	IValue_t	 acpcPeriod;
	BIT_STRING_t	 childNodeId;
	OCTET_STRING_t	 parentNodeValue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AprvHashCalculationInput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AprvHashCalculationInput;

#ifdef __cplusplus
}
#endif

#endif	/* _AprvHashCalculationInput_H_ */
#include <asn_internal.h>
