/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_CertificateFormat (1)
#define max_val_CertificateFormat (255)
#define min_val_PduFunctionalType (0)
#define max_val_PduFunctionalType (255)
#define min_val_HeaderInfoContributorId (0)
#define max_val_HeaderInfoContributorId (255)
#define min_val_Uint3 (0)
#define max_val_Uint3 (7)
#define min_val_Uint8 (0)
#define max_val_Uint8 (255)
#define min_val_Uint16 (0)
#define max_val_Uint16 (65535)
#define min_val_Uint32 (0)
#define max_val_Uint32 (4294967295)
#define min_val_Uint64 (0)
#define max_val_Uint64 (18446744073709551615ULL)
#define min_val_NinetyDegreeInt (-900000000)
#define max_val_NinetyDegreeInt (900000001)
#define min_val_OneEightyDegreeInt (-1799999999)
#define max_val_OneEightyDegreeInt (1800000001)
#define min_val_Psid (0)
#define max_val_Psid (321)
#define min_val_ExtId (0)
#define max_val_ExtId (255)
#define min_val_Ieee1609dot2dot1MsctlType (0)
#define max_val_Ieee1609dot2dot1MsctlType (255)
#define min_val_CtlSequenceNumber (0)
#define max_val_CtlSequenceNumber (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
