/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TypesAuthorizationValidation"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TypesAuthorizationValidation.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#include "AuthorizationValidationResponseCode.h"
#include <constr_SEQUENCE.h>
#ifndef	_AuthorizationValidationResponse_H_
#define	_AuthorizationValidationResponse_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateSubjectAttributes;

/* AuthorizationValidationResponse */
typedef struct AuthorizationValidationResponse {
	OCTET_STRING_t	 requestHash;
	AuthorizationValidationResponseCode_t	 responseCode;
	struct CertificateSubjectAttributes	*confirmedSubjectAttributes;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthorizationValidationResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthorizationValidationResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthorizationValidationResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthorizationValidationResponse_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateSubjectAttributes.h"

#endif	/* _AuthorizationValidationResponse_H_ */
#include <asn_internal.h>
