/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EeRaInterface"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1EeRaInterface.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>
#ifndef	_ButterflyExpansion_H_
#define	_ButterflyExpansion_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ButterflyExpansion_PR {
	ButterflyExpansion_PR_NOTHING,	/* No components present */
	ButterflyExpansion_PR_aes128
	/* Extensions may appear below */
	
} ButterflyExpansion_PR;

/* ButterflyExpansion */
typedef struct ButterflyExpansion {
	ButterflyExpansion_PR present;
	union ButterflyExpansion_u {
		OCTET_STRING_t	 aes128;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ButterflyExpansion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ButterflyExpansion;
extern asn_CHOICE_specifics_t asn_SPC_ButterflyExpansion_specs_1;
extern asn_TYPE_member_t asn_MBR_ButterflyExpansion_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _ButterflyExpansion_H_ */
#include <asn_internal.h>
