/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941MessagesCa"
 * 	found in "asn1/pki_ts102941/EtsiTs102941MessagesCa.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "EtsiTs103097Data-Signed.h"
#ifndef	_CaCertificateRekeyingMessage_H_
#define	_CaCertificateRekeyingMessage_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CaCertificateRekeyingMessage */
typedef EtsiTs103097Data_Signed_63P1_t	 CaCertificateRekeyingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CaCertificateRekeyingMessage;
asn_struct_free_f CaCertificateRekeyingMessage_free;
asn_struct_print_f CaCertificateRekeyingMessage_print;
asn_constr_check_f CaCertificateRekeyingMessage_constraint;
xer_type_decoder_f CaCertificateRekeyingMessage_decode_xer;
xer_type_encoder_f CaCertificateRekeyingMessage_encode_xer;
oer_type_decoder_f CaCertificateRekeyingMessage_decode_oer;
oer_type_encoder_f CaCertificateRekeyingMessage_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _CaCertificateRekeyingMessage_H_ */
#include <asn_internal.h>
