/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CamRaInterface"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1CamRaInterface.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "RaCamBatchRequest.h"
#include "CamRaBatchResponse.h"
#include <constr_CHOICE.h>
#ifndef	_CamRaInterfacePdu_H_
#define	_CamRaInterfacePdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CamRaInterfacePdu_PR {
	CamRaInterfacePdu_PR_NOTHING,	/* No components present */
	CamRaInterfacePdu_PR_raCamBatchRequest,
	CamRaInterfacePdu_PR_camRaBatchResponse
	/* Extensions may appear below */
	
} CamRaInterfacePdu_PR;

/* CamRaInterfacePdu */
typedef struct CamRaInterfacePdu {
	CamRaInterfacePdu_PR present;
	union CamRaInterfacePdu_u {
		RaCamBatchRequest_t	 raCamBatchRequest;
		CamRaBatchResponse_t	 camRaBatchResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamRaInterfacePdu;

#ifdef __cplusplus
}
#endif

#endif	/* _CamRaInterfacePdu_H_ */
#include <asn_internal.h>
