/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "ExtId.h"
#include <asn_ioc.h>
#include "OperatingOrganizationId.h"
#include <NULL.h>
#include <ANY.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_CertIssueExtension_H_
#define	_CertIssueExtension_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CertIssueExtension__permissions_PR {
	CertIssueExtension__permissions_PR_NOTHING,	/* No components present */
	CertIssueExtension__permissions_PR_specific,
	CertIssueExtension__permissions_PR_all
} CertIssueExtension__permissions_PR;

/* CertIssueExtension */
typedef struct CertIssueExtension {
	ExtId_t	 id;
	struct CertIssueExtension__permissions {
		CertIssueExtension__permissions_PR present;
		union CertIssueExtension__permissions_u {
			ANY_t	 specific;
			NULL_t	 all;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} permissions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertIssueExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertIssueExtension;
extern asn_SEQUENCE_specifics_t asn_SPC_CertIssueExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_CertIssueExtension_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CertIssueExtension_H_ */
#include <asn_internal.h>
