/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "SequenceOfCrlInfoStatus.h"
#include "SequenceOfCtlInfoStatus.h"
#include "Time32.h"
#include "SequenceOfMaInfoStatus.h"
#include <constr_SEQUENCE.h>
#ifndef	_CertificateManagementInfoStatus_H_
#define	_CertificateManagementInfoStatus_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateManagementInfoStatus */
typedef struct CertificateManagementInfoStatus {
	SequenceOfCrlInfoStatus_t	 crl;
	SequenceOfCtlInfoStatus_t	 ctl;
	Time32_t	 caCcf;
	SequenceOfMaInfoStatus_t	 ma;
	Time32_t	*ra;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateManagementInfoStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateManagementInfoStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_CertificateManagementInfoStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateManagementInfoStatus_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateManagementInfoStatus_H_ */
#include <asn_internal.h>
