/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/IEEE1609dot2.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Ieee1609Dot2Data.h"
#ifndef	_Countersignature_H_
#define	_Countersignature_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Countersignature */
typedef Ieee1609Dot2Data_t	 Countersignature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Countersignature;
asn_struct_free_f Countersignature_free;
asn_struct_print_f Countersignature_print;
asn_constr_check_f Countersignature_constraint;
xer_type_decoder_f Countersignature_decode_xer;
xer_type_encoder_f Countersignature_encode_xer;
oer_type_decoder_f Countersignature_decode_oer;
oer_type_encoder_f Countersignature_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Countersignature_H_ */
#include <asn_internal.h>
