/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Crl"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2Crl.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Psid.h"
#ifndef	_CrlPsid_H_
#define	_CrlPsid_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CrlPsid */
typedef Psid_t	 CrlPsid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlPsid;
asn_struct_free_f CrlPsid_free;
asn_struct_print_f CrlPsid_print;
asn_constr_check_f CrlPsid_constraint;
xer_type_decoder_f CrlPsid_decode_xer;
xer_type_encoder_f CrlPsid_encode_xer;
oer_type_decoder_f CrlPsid_decode_oer;
oer_type_encoder_f CrlPsid_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlPsid_H_ */
#include <asn_internal.h>
