/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TrustLists.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "HashedId8.h"
#include "DcDelete.h"
#include <constr_CHOICE.h>
#ifndef	_CtlDelete_H_
#define	_CtlDelete_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CtlDelete_PR {
	CtlDelete_PR_NOTHING,	/* No components present */
	CtlDelete_PR_cert,
	CtlDelete_PR_dc
	/* Extensions may appear below */
	
} CtlDelete_PR;

/* CtlDelete */
typedef struct CtlDelete {
	CtlDelete_PR present;
	union CtlDelete_u {
		HashedId8_t	 cert;
		DcDelete_t	 dc;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CtlDelete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtlDelete;
extern asn_CHOICE_specifics_t asn_SPC_CtlDelete_specs_1;
extern asn_TYPE_member_t asn_MBR_CtlDelete_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CtlDelete_H_ */
#include <asn_internal.h>
