/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "HashedId48.h"
#ifndef	_CtlElectorEntry_H_
#define	_CtlElectorEntry_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CtlElectorEntry */
typedef HashedId48_t	 CtlElectorEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtlElectorEntry;
asn_struct_free_f CtlElectorEntry_free;
asn_struct_print_f CtlElectorEntry_print;
asn_constr_check_f CtlElectorEntry_constraint;
xer_type_decoder_f CtlElectorEntry_decode_xer;
xer_type_encoder_f CtlElectorEntry_encode_xer;
oer_type_decoder_f CtlElectorEntry_decode_oer;
oer_type_encoder_f CtlElectorEntry_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _CtlElectorEntry_H_ */
#include <asn_internal.h>
