/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TrustLists.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "EtsiTs103097Certificate.h"
#include "Url.h"
#include <constr_SEQUENCE.h>
#ifndef	_EaEntry_H_
#define	_EaEntry_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EaEntry */
typedef struct EaEntry {
	EtsiTs103097Certificate_t	 eaCertificate;
	Url_t	 aaAccessPoint;
	Url_t	*itsAccessPoint;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EaEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EaEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_EaEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_EaEntry_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EaEntry_H_ */
#include <asn_internal.h>
