/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941BaseTypes"
 * 	found in "asn1/pki_ts102941/EtsiTs102941BaseTypes.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "EtsiTs103097Data-Encrypted.h"
#include "EtsiTs103097Data-SignedExternalPayload.h"
#include <constr_CHOICE.h>
#ifndef	_EcSignature_H_
#define	_EcSignature_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EcSignature_PR {
	EcSignature_PR_NOTHING,	/* No components present */
	EcSignature_PR_encryptedEcSignature,
	EcSignature_PR_ecSignature
} EcSignature_PR;

/* EcSignature */
typedef struct EcSignature {
	EcSignature_PR present;
	union EcSignature_u {
		EtsiTs103097Data_Encrypted_93P2_t	 encryptedEcSignature;
		EtsiTs103097Data_SignedExternalPayload_t	 ecSignature;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EcSignature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcSignature;
extern asn_CHOICE_specifics_t asn_SPC_EcSignature_specs_1;
extern asn_TYPE_member_t asn_MBR_EcSignature_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EcSignature_H_ */
#include <asn_internal.h>
