/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TypesAuthorization"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TypesAuthorization.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Ieee1609Dot2Data-SignedX509AuthenticatedCertRequest.h"
#ifndef	_EtsiTs102941ButterflyAuthorizationRequest_X509Signed_H_
#define	_EtsiTs102941ButterflyAuthorizationRequest_X509Signed_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs102941ButterflyAuthorizationRequest-X509Signed */
typedef Ieee1609Dot2Data_SignedX509AuthenticatedCertRequest_335P0_t	 EtsiTs102941ButterflyAuthorizationRequest_X509Signed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs102941ButterflyAuthorizationRequest_X509Signed;
asn_struct_free_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_free;
asn_struct_print_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_print;
asn_constr_check_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_constraint;
xer_type_decoder_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_decode_xer;
xer_type_encoder_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_encode_xer;
oer_type_decoder_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_decode_oer;
oer_type_encoder_f EtsiTs102941ButterflyAuthorizationRequest_X509Signed_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs102941ButterflyAuthorizationRequest_X509Signed_H_ */
#include <asn_internal.h>
