/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "asn1/sec_ts103097/EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Extension.h"
#ifndef	_EtsiOriginatingHeaderInfoExtension_H_
#define	_EtsiOriginatingHeaderInfoExtension_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiOriginatingHeaderInfoExtension */
typedef EtsiTs103097HeaderInfoExtensions_t	 EtsiOriginatingHeaderInfoExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiOriginatingHeaderInfoExtension;
asn_struct_free_f EtsiOriginatingHeaderInfoExtension_free;
asn_struct_print_f EtsiOriginatingHeaderInfoExtension_print;
asn_constr_check_f EtsiOriginatingHeaderInfoExtension_constraint;
xer_type_decoder_f EtsiOriginatingHeaderInfoExtension_decode_xer;
xer_type_encoder_f EtsiOriginatingHeaderInfoExtension_encode_xer;
oer_type_decoder_f EtsiOriginatingHeaderInfoExtension_decode_oer;
oer_type_encoder_f EtsiOriginatingHeaderInfoExtension_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiOriginatingHeaderInfoExtension_H_ */
#include <asn_internal.h>
