/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_ExpansionAlgorithmIdentifier_H_
#define	_ExpansionAlgorithmIdentifier_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExpansionAlgorithmIdentifier {
	ExpansionAlgorithmIdentifier_sha256ForI_aesForJ	= 0,
	ExpansionAlgorithmIdentifier_sm3ForI_sm4ForJ	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ExpansionAlgorithmIdentifier;

/* ExpansionAlgorithmIdentifier */
typedef long	 ExpansionAlgorithmIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExpansionAlgorithmIdentifier;
asn_struct_free_f ExpansionAlgorithmIdentifier_free;
asn_struct_print_f ExpansionAlgorithmIdentifier_print;
asn_constr_check_f ExpansionAlgorithmIdentifier_constraint;
xer_type_decoder_f ExpansionAlgorithmIdentifier_decode_xer;
xer_type_encoder_f ExpansionAlgorithmIdentifier_encode_xer;
oer_type_decoder_f ExpansionAlgorithmIdentifier_decode_oer;
oer_type_encoder_f ExpansionAlgorithmIdentifier_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExpansionAlgorithmIdentifier_H_ */
#include <asn_internal.h>
