/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "asn1/sec_ts103097/EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ExtensionModuleVersion_H_
#define	_ExtensionModuleVersion_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtensionModuleVersion */
typedef long	 ExtensionModuleVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtensionModuleVersion;
asn_struct_free_f ExtensionModuleVersion_free;
asn_struct_print_f ExtensionModuleVersion_print;
asn_constr_check_f ExtensionModuleVersion_constraint;
xer_type_decoder_f ExtensionModuleVersion_decode_xer;
xer_type_encoder_f ExtensionModuleVersion_encode_xer;
oer_type_decoder_f ExtensionModuleVersion_decode_oer;
oer_type_encoder_f ExtensionModuleVersion_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtensionModuleVersion_H_ */
#include <asn_internal.h>
