/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Uint16.h"
#include "LaId.h"
#include "LinkageSeed.h"
#include <constr_SEQUENCE.h>
#ifndef	_GroupCrlEntry_H_
#define	_GroupCrlEntry_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GroupCrlEntry */
typedef struct GroupCrlEntry {
	Uint16_t	 iMax;
	LaId_t	 la1Id;
	LinkageSeed_t	 linkageSeed1;
	LaId_t	 la2Id;
	LinkageSeed_t	 linkageSeed2;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupCrlEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupCrlEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupCrlEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_GroupCrlEntry_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _GroupCrlEntry_H_ */
#include <asn_internal.h>
