/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "HashedId32.h"
#include "HashedId48.h"
#include <constr_CHOICE.h>
#ifndef	_HashedData_H_
#define	_HashedData_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HashedData_PR {
	HashedData_PR_NOTHING,	/* No components present */
	HashedData_PR_sha256HashedData,
	/* Extensions may appear below */
	HashedData_PR_sha384HashedData,
	HashedData_PR_sm3HashedData
} HashedData_PR;

/* HashedData */
typedef struct HashedData {
	HashedData_PR present;
	union HashedData_u {
		HashedId32_t	 sha256HashedData;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		HashedId48_t	 sha384HashedData;
		HashedId32_t	 sm3HashedData;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HashedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HashedData;
extern asn_CHOICE_specifics_t asn_SPC_HashedData_specs_1;
extern asn_TYPE_member_t asn_MBR_HashedData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _HashedData_H_ */
#include <asn_internal.h>
