/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Ieee1609dot2dot1MsctlType_H_
#define	_Ieee1609dot2dot1MsctlType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ieee1609dot2dot1MsctlType */
typedef long	 Ieee1609dot2dot1MsctlType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609dot2dot1MsctlType;
asn_struct_free_f Ieee1609dot2dot1MsctlType_free;
asn_struct_print_f Ieee1609dot2dot1MsctlType_print;
asn_constr_check_f Ieee1609dot2dot1MsctlType_constraint;
xer_type_decoder_f Ieee1609dot2dot1MsctlType_decode_xer;
xer_type_encoder_f Ieee1609dot2dot1MsctlType_encode_xer;
oer_type_decoder_f Ieee1609dot2dot1MsctlType_decode_oer;
oer_type_encoder_f Ieee1609dot2dot1MsctlType_encode_oer;
#define Ieee1609dot2dot1MsctlType_fullIeeeCtl	((Ieee1609dot2dot1MsctlType_t)1)

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609dot2dot1MsctlType_H_ */
#include <asn_internal.h>
