/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Ieee1609Dot2Data.h"
#ifndef	_Ieee1609Dot2Data_Encrypted_H_
#define	_Ieee1609Dot2Data_Encrypted_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ieee1609Dot2Data-Encrypted */
typedef Ieee1609Dot2Data_t	 Ieee1609Dot2Data_Encrypted_276P0_t;
typedef Ieee1609Dot2Data_t	 Ieee1609Dot2Data_Encrypted_276P1_t;
typedef Ieee1609Dot2Data_t	 Ieee1609Dot2Data_Encrypted_276P2_t;
typedef Ieee1609Dot2Data_t	 Ieee1609Dot2Data_Encrypted_276P3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2Data_Encrypted_276P0;
asn_struct_free_f Ieee1609Dot2Data_Encrypted_276P0_free;
asn_struct_print_f Ieee1609Dot2Data_Encrypted_276P0_print;
asn_constr_check_f Ieee1609Dot2Data_Encrypted_276P0_constraint;
xer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P0_decode_xer;
xer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P0_encode_xer;
oer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P0_decode_oer;
oer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P0_encode_oer;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2Data_Encrypted_276P1;
asn_struct_free_f Ieee1609Dot2Data_Encrypted_276P1_free;
asn_struct_print_f Ieee1609Dot2Data_Encrypted_276P1_print;
asn_constr_check_f Ieee1609Dot2Data_Encrypted_276P1_constraint;
xer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P1_decode_xer;
xer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P1_encode_xer;
oer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P1_decode_oer;
oer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P1_encode_oer;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2Data_Encrypted_276P2;
asn_struct_free_f Ieee1609Dot2Data_Encrypted_276P2_free;
asn_struct_print_f Ieee1609Dot2Data_Encrypted_276P2_print;
asn_constr_check_f Ieee1609Dot2Data_Encrypted_276P2_constraint;
xer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P2_decode_xer;
xer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P2_encode_xer;
oer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P2_decode_oer;
oer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P2_encode_oer;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot2Data_Encrypted_276P3;
asn_struct_free_f Ieee1609Dot2Data_Encrypted_276P3_free;
asn_struct_print_f Ieee1609Dot2Data_Encrypted_276P3_print;
asn_constr_check_f Ieee1609Dot2Data_Encrypted_276P3_constraint;
xer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P3_decode_xer;
xer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P3_encode_xer;
oer_type_decoder_f Ieee1609Dot2Data_Encrypted_276P3_decode_oer;
oer_type_encoder_f Ieee1609Dot2Data_Encrypted_276P3_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609Dot2Data_Encrypted_H_ */
#include <asn_internal.h>
