/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1LaRaInterface"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1LaRaInterface.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NULL.h>
#ifndef	_LaRaInterfacePdu_H_
#define	_LaRaInterfacePdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LaRaInterfacePdu */
typedef NULL_t	 LaRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaRaInterfacePdu;
asn_struct_free_f LaRaInterfacePdu_free;
asn_struct_print_f LaRaInterfacePdu_print;
asn_constr_check_f LaRaInterfacePdu_constraint;
xer_type_decoder_f LaRaInterfacePdu_decode_xer;
xer_type_encoder_f LaRaInterfacePdu_encode_xer;
oer_type_decoder_f LaRaInterfacePdu_decode_oer;
oer_type_encoder_f LaRaInterfacePdu_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _LaRaInterfacePdu_H_ */
#include <asn_internal.h>
