/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NULL.h>
#ifndef	_LvGenerationFunctionIdentifier_H_
#define	_LvGenerationFunctionIdentifier_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LvGenerationFunctionIdentifier */
typedef NULL_t	 LvGenerationFunctionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LvGenerationFunctionIdentifier;
asn_struct_free_f LvGenerationFunctionIdentifier_free;
asn_struct_print_f LvGenerationFunctionIdentifier_print;
asn_constr_check_f LvGenerationFunctionIdentifier_constraint;
xer_type_decoder_f LvGenerationFunctionIdentifier_decode_xer;
xer_type_encoder_f LvGenerationFunctionIdentifier_encode_xer;
oer_type_decoder_f LvGenerationFunctionIdentifier_decode_oer;
oer_type_encoder_f LvGenerationFunctionIdentifier_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _LvGenerationFunctionIdentifier_H_ */
#include <asn_internal.h>
