/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/IEEE1609dot2.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_PduFunctionalType_H_
#define	_PduFunctionalType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PduFunctionalType */
typedef long	 PduFunctionalType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PduFunctionalType;
asn_struct_free_f PduFunctionalType_free;
asn_struct_print_f PduFunctionalType_print;
asn_constr_check_f PduFunctionalType_constraint;
xer_type_decoder_f PduFunctionalType_decode_xer;
xer_type_encoder_f PduFunctionalType_encode_xer;
oer_type_decoder_f PduFunctionalType_decode_oer;
oer_type_encoder_f PduFunctionalType_encode_oer;
#define PduFunctionalType_tlsHandshake	((PduFunctionalType_t)1)
#define PduFunctionalType_iso21177ExtendedAuth	((PduFunctionalType_t)2)
#define PduFunctionalType_iso21177SessionExtension	((PduFunctionalType_t)3)

#ifdef __cplusplus
}
#endif

#endif	/* _PduFunctionalType_H_ */
#include <asn_internal.h>
