/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1AcaRaInterface"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1AcaRaInterface.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <BIT_STRING.h>
#ifndef	_RaAcaCertRequestFlags_H_
#define	_RaAcaCertRequestFlags_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RaAcaCertRequestFlags {
	RaAcaCertRequestFlags_butterflyExplicit	= 0,
	RaAcaCertRequestFlags_cubk	= 1
} e_RaAcaCertRequestFlags;

/* RaAcaCertRequestFlags */
typedef BIT_STRING_t	 RaAcaCertRequestFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaAcaCertRequestFlags;
asn_struct_free_f RaAcaCertRequestFlags_free;
asn_struct_print_f RaAcaCertRequestFlags_print;
asn_constr_check_f RaAcaCertRequestFlags_constraint;
xer_type_decoder_f RaAcaCertRequestFlags_decode_xer;
xer_type_encoder_f RaAcaCertRequestFlags_encode_xer;
oer_type_decoder_f RaAcaCertRequestFlags_decode_oer;
oer_type_encoder_f RaAcaCertRequestFlags_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _RaAcaCertRequestFlags_H_ */
#include <asn_internal.h>
