/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "EccP256CurvePoint.h"
#ifndef	_ReconstructionValue_H_
#define	_ReconstructionValue_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReconstructionValue */
typedef EccP256CurvePoint_t	 ReconstructionValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReconstructionValue;
asn_struct_free_f ReconstructionValue_free;
asn_struct_print_f ReconstructionValue_print;
asn_constr_check_f ReconstructionValue_constraint;
xer_type_decoder_f ReconstructionValue_decode_xer;
xer_type_encoder_f ReconstructionValue_encode_xer;
oer_type_decoder_f ReconstructionValue_decode_oer;
oer_type_encoder_f ReconstructionValue_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReconstructionValue_H_ */
#include <asn_internal.h>
