/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "ScmsPdu.h"
#ifndef	_ScmsPdu_Scoped_H_
#define	_ScmsPdu_Scoped_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScmsPdu-Scoped */
typedef ScmsPdu_t	 ScmsPdu_Scoped_204P0_t;
typedef ScmsPdu_t	 ScmsPdu_Scoped_204P1_t;
typedef ScmsPdu_t	 ScmsPdu_Scoped_204P2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_Scoped_204P0;
asn_struct_free_f ScmsPdu_Scoped_204P0_free;
asn_struct_print_f ScmsPdu_Scoped_204P0_print;
asn_constr_check_f ScmsPdu_Scoped_204P0_constraint;
xer_type_decoder_f ScmsPdu_Scoped_204P0_decode_xer;
xer_type_encoder_f ScmsPdu_Scoped_204P0_encode_xer;
oer_type_decoder_f ScmsPdu_Scoped_204P0_decode_oer;
oer_type_encoder_f ScmsPdu_Scoped_204P0_encode_oer;
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_Scoped_204P1;
asn_struct_free_f ScmsPdu_Scoped_204P1_free;
asn_struct_print_f ScmsPdu_Scoped_204P1_print;
asn_constr_check_f ScmsPdu_Scoped_204P1_constraint;
xer_type_decoder_f ScmsPdu_Scoped_204P1_decode_xer;
xer_type_encoder_f ScmsPdu_Scoped_204P1_encode_xer;
oer_type_decoder_f ScmsPdu_Scoped_204P1_decode_oer;
oer_type_encoder_f ScmsPdu_Scoped_204P1_encode_oer;
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_Scoped_204P2;
asn_struct_free_f ScmsPdu_Scoped_204P2_free;
asn_struct_print_f ScmsPdu_Scoped_204P2_print;
asn_constr_check_f ScmsPdu_Scoped_204P2_constraint;
xer_type_decoder_f ScmsPdu_Scoped_204P2_decode_xer;
xer_type_encoder_f ScmsPdu_Scoped_204P2_encode_xer;
oer_type_decoder_f ScmsPdu_Scoped_204P2_decode_oer;
oer_type_encoder_f ScmsPdu_Scoped_204P2_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_Scoped_H_ */
#include <asn_internal.h>
