/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "asn1/ieee1609.2.1/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "ElectorSsp.h"
#include "RootCaSsp.h"
#include "PgSsp.h"
#include "IcaSsp.h"
#include "EcaSsp.h"
#include "AcaSsp.h"
#include "CrlSignerSsp.h"
#include "DcmSsp.h"
#include "LaSsp.h"
#include "LopSsp.h"
#include "MaSsp.h"
#include "RaSsp.h"
#include "EeSsp.h"
#include "DcSsp.h"
#include <constr_CHOICE.h>
#ifndef	_SecurityMgmtSsp_H_
#define	_SecurityMgmtSsp_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityMgmtSsp_PR {
	SecurityMgmtSsp_PR_NOTHING,	/* No components present */
	SecurityMgmtSsp_PR_elector,
	SecurityMgmtSsp_PR_root,
	SecurityMgmtSsp_PR_pg,
	SecurityMgmtSsp_PR_ica,
	SecurityMgmtSsp_PR_eca,
	SecurityMgmtSsp_PR_aca,
	SecurityMgmtSsp_PR_crl,
	SecurityMgmtSsp_PR_dcm,
	SecurityMgmtSsp_PR_la,
	SecurityMgmtSsp_PR_lop,
	SecurityMgmtSsp_PR_ma,
	SecurityMgmtSsp_PR_ra,
	SecurityMgmtSsp_PR_ee,
	/* Extensions may appear below */
	SecurityMgmtSsp_PR_dc
} SecurityMgmtSsp_PR;

/* SecurityMgmtSsp */
typedef struct SecurityMgmtSsp {
	SecurityMgmtSsp_PR present;
	union SecurityMgmtSsp_u {
		ElectorSsp_t	 elector;
		RootCaSsp_t	 root;
		PgSsp_t	 pg;
		IcaSsp_t	 ica;
		EcaSsp_t	 eca;
		AcaSsp_t	 aca;
		CrlSignerSsp_t	 crl;
		DcmSsp_t	 dcm;
		LaSsp_t	 la;
		LopSsp_t	 lop;
		MaSsp_t	 ma;
		RaSsp_t	 ra;
		EeSsp_t	 ee;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		DcSsp_t	 dc;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityMgmtSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtSsp;
extern asn_CHOICE_specifics_t asn_SPC_SecurityMgmtSsp_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityMgmtSsp_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtSsp_H_ */
#include <asn_internal.h>
