/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TypesAuthorization"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TypesAuthorization.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "HashedId8.h"
#include <OCTET_STRING.h>
#include "CertificateFormat.h"
#include "CertificateSubjectAttributes.h"
#include <constr_SEQUENCE.h>
#ifndef	_SharedAtRequest_H_
#define	_SharedAtRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SharedAtRequest */
typedef struct SharedAtRequest {
	HashedId8_t	 eaId;
	OCTET_STRING_t	 keyTag;
	CertificateFormat_t	 certificateFormat;
	CertificateSubjectAttributes_t	 requestedSubjectAttributes;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedAtRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SharedAtRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SharedAtRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedAtRequest_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SharedAtRequest_H_ */
#include <asn_internal.h>
