/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "asn1/ieee1609.2/IEEE1609dot2BaseTypes.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_SymmAlgorithm_H_
#define	_SymmAlgorithm_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SymmAlgorithm {
	SymmAlgorithm_aes128Ccm	= 0,
	/*
	 * Enumeration is extensible
	 */
	SymmAlgorithm_sm4Ccm	= 1
} e_SymmAlgorithm;

/* SymmAlgorithm */
typedef long	 SymmAlgorithm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SymmAlgorithm;
extern const asn_INTEGER_specifics_t asn_SPC_SymmAlgorithm_specs_1;
asn_struct_free_f SymmAlgorithm_free;
asn_struct_print_f SymmAlgorithm_print;
asn_constr_check_f SymmAlgorithm_constraint;
xer_type_decoder_f SymmAlgorithm_decode_xer;
xer_type_encoder_f SymmAlgorithm_encode_xer;
oer_type_decoder_f SymmAlgorithm_decode_oer;
oer_type_encoder_f SymmAlgorithm_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SymmAlgorithm_H_ */
#include <asn_internal.h>
