/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TypesLinkCertificate"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TypesLinkCertificate.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "ToBeSignedLinkCertificate.h"
#ifndef	_ToBeSignedLinkCertificateRca_H_
#define	_ToBeSignedLinkCertificateRca_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedLinkCertificateRca */
typedef ToBeSignedLinkCertificate_t	 ToBeSignedLinkCertificateRca_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedLinkCertificateRca;
asn_struct_free_f ToBeSignedLinkCertificateRca_free;
asn_struct_print_f ToBeSignedLinkCertificateRca_print;
asn_constr_check_f ToBeSignedLinkCertificateRca_constraint;
xer_type_decoder_f ToBeSignedLinkCertificateRca_decode_xer;
xer_type_encoder_f ToBeSignedLinkCertificateRca_encode_xer;
oer_type_decoder_f ToBeSignedLinkCertificateRca_decode_oer;
oer_type_encoder_f ToBeSignedLinkCertificateRca_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedLinkCertificateRca_H_ */
#include <asn_internal.h>
