/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "ToBeSignedHashIdCrl.h"
#include "ToBeSignedLinkageValueCrl.h"
#include "ToBeSignedLinkageValueCrlWithAlgIdentifier.h"
#include <constr_CHOICE.h>
#ifndef	_TypeSpecificCrlContents_H_
#define	_TypeSpecificCrlContents_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TypeSpecificCrlContents_PR {
	TypeSpecificCrlContents_PR_NOTHING,	/* No components present */
	TypeSpecificCrlContents_PR_fullHashCrl,
	TypeSpecificCrlContents_PR_deltaHashCrl,
	TypeSpecificCrlContents_PR_fullLinkedCrl,
	TypeSpecificCrlContents_PR_deltaLinkedCrl,
	/* Extensions may appear below */
	TypeSpecificCrlContents_PR_fullLinkedCrlWithAlg,
	TypeSpecificCrlContents_PR_deltaLinkedCrlWithAlg
} TypeSpecificCrlContents_PR;

/* TypeSpecificCrlContents */
typedef struct TypeSpecificCrlContents {
	TypeSpecificCrlContents_PR present;
	union TypeSpecificCrlContents_u {
		ToBeSignedHashIdCrl_t	 fullHashCrl;
		ToBeSignedHashIdCrl_t	 deltaHashCrl;
		ToBeSignedLinkageValueCrl_t	 fullLinkedCrl;
		ToBeSignedLinkageValueCrl_t	 deltaLinkedCrl;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		ToBeSignedLinkageValueCrlWithAlgIdentifier_t	 fullLinkedCrlWithAlg;
		ToBeSignedLinkageValueCrlWithAlgIdentifier_t	 deltaLinkedCrlWithAlg;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TypeSpecificCrlContents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeSpecificCrlContents;
extern asn_CHOICE_specifics_t asn_SPC_TypeSpecificCrlContents_specs_1;
extern asn_TYPE_member_t asn_MBR_TypeSpecificCrlContents_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _TypeSpecificCrlContents_H_ */
#include <asn_internal.h>
