/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "asn1/ieee1609.2/IEEE1609dot2BaseTypes.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "Uint16.h"
#ifndef	_UnCountryId_H_
#define	_UnCountryId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnCountryId */
typedef Uint16_t	 UnCountryId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnCountryId;
asn_struct_free_f UnCountryId_free;
asn_struct_print_f UnCountryId_print;
asn_constr_check_f UnCountryId_constraint;
xer_type_decoder_f UnCountryId_decode_xer;
xer_type_encoder_f UnCountryId_encode_xer;
oer_type_decoder_f UnCountryId_decode_oer;
oer_type_encoder_f UnCountryId_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnCountryId_H_ */
#include <asn_internal.h>
