/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "asn1/pki_ts102941/EtsiTs102941TrustLists.asn"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include <IA5String.h>
#ifndef	_Url_H_
#define	_Url_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Url */
typedef IA5String_t	 Url_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Url;
asn_struct_free_f Url_free;
asn_struct_print_f Url_print;
asn_constr_check_f Url_constraint;
xer_type_decoder_f Url_decode_xer;
xer_type_encoder_f Url_encode_xer;
oer_type_decoder_f Url_decode_oer;
oer_type_encoder_f Url_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Url_H_ */
#include <asn_internal.h>
