/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "asn1/ieee1609.2/Ieee1609Dot2.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "PublicVerificationKey.h"
#include "ReconstructionValue.h"
#include <constr_CHOICE.h>
#ifndef	_VerificationKeyIndicator_H_
#define	_VerificationKeyIndicator_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerificationKeyIndicator_PR {
	VerificationKeyIndicator_PR_NOTHING,	/* No components present */
	VerificationKeyIndicator_PR_verificationKey,
	VerificationKeyIndicator_PR_reconstructionValue
	/* Extensions may appear below */
	
} VerificationKeyIndicator_PR;

/* VerificationKeyIndicator */
typedef struct VerificationKeyIndicator {
	VerificationKeyIndicator_PR present;
	union VerificationKeyIndicator_u {
		PublicVerificationKey_t	 verificationKey;
		ReconstructionValue_t	 reconstructionValue;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerificationKeyIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerificationKeyIndicator;
extern asn_CHOICE_specifics_t asn_SPC_VerificationKeyIndicator_specs_1;
extern asn_TYPE_member_t asn_MBR_VerificationKeyIndicator_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VerificationKeyIndicator_H_ */
#include <asn_internal.h>
