/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ASN1C-DATE"
 * 	found in "../../../../asn1c-fillabs2/skeletons/standard-modules/date.asn1"
 * 	`asn1c -S ../../../../asn1c-fillabs2/skeletons -fcompound-names -no-gen-BER -no-gen-JER -no-gen-UPER -no-gen-APER -no-gen-random-fill -no-gen-example -pdu=EtsiTs103097Data -pdu=EnrolmentRequestMessage -pdu=EnrolmentResponseMessage -pdu=AuthorizationRequestMessage -pdu=AuthorizationRequestMessageWithPop -pdu=AuthorizationResponseMessage -pdu=CertificateRevocationListMessage -pdu=TlmCertificateTrustListMessage -pdu=RcaCertificateTrustListMessage -pdu=AuthorizationValidationRequestMessage -pdu=AuthorizationValidationResponseMessage -pdu=CaCertificateRequestMessage -pdu=EtsiTs103097Certificate`
 */


/* Including external dependencies */
#include "YEAR-ENCODING.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#ifndef	_YEAR_MONTH_ENCODING_H_
#define	_YEAR_MONTH_ENCODING_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* YEAR-MONTH-ENCODING */
typedef struct YEAR_MONTH_ENCODING {
	YEAR_ENCODING_t	 year;
	long	 month;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} YEAR_MONTH_ENCODING_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_YEAR_MONTH_ENCODING;

#ifdef __cplusplus
}
#endif

#endif	/* _YEAR_MONTH_ENCODING_H_ */
#include <asn_internal.h>
